name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name != 'pull_request'
    runs-on: [self-hosted, skippr-linux-x64-16]
    steps:
      - uses: actions/checkout@v4
      - name: Package
        run: test -f package.json && test -f custom.css && test -f theme.js
